version: "3.9"

# Configure the service here
x-common-variables: &common-variables
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: audio
  DATABASE_URL: postgres://postgres:postgres@localhost:5433/audio

services:
  server:
    image: ghcr.io/angelsflyinhell/audio-server:latest
    container_name: audio_server
    restart: unless-stopped
    ports:
      - 4300:80
    environment:
      <<: *common-variables
    depends_on:
      - db
    networks:
      - audio
      
  db:
    image: postgres:latest
    container_name: audio_db_1
    restart: unless-stopped
    environment:
      <<: *common-variables
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - audio

networks:
  default:
      name: audio